const formats = {
  item: {
    'item.title': 'The Wines of Italy',
    'item.primaryContributor': 'Thomas, George B.',
    'item.allContributors': 'Finney, Ross L.; Weir, Maurice D.',
    'item.barcode': '31924001521792',
    'item.barcodeImage': '<Barcode>31924001521792</Barcode>',
    'item.callNumber': 'TK7871.15.F4 S67 1988',
    'item.callNumberPrefix': 'New & Noteworthy',
    'item.callNumberSuffix': 'Handbook',
    'item.enumeration': 'no.1-3',
    'item.volume': 'v. 27',
    'item.chronology': '1964-1967 (Board)',
    'item.yearCaption': 'Convention photographs 1911-1960',
    'item.materialType': 'Serial',
    'item.copy': 'c.2',
    'item.numberOfPieces': '7',
    'item.descriptionOfPieces': '7 maps in pocket',
  },
  user: {
    'user.firstName': 'John',
    'user.lastName': 'Smith',
    'user.middleName': 'Adam',
    'user.barcode': '456123789',
    'user.barcodeImage': '<Barcode>456123789</Barcode>',
  },
  request: {
    'request.servicePointPickup': 'Circulation Desk - Main Library',
    'request.requestExpirationDate': 'Mar 31 30, 2020',
    'request.requestExpirationDateTime': 'Mar 31, 2020 23:59',
    'request.holdShelfExpirationDate': 'Jun 30, 2020',
    'request.holdShelfExpirationDateTime': 'Jun 30, 2020 23:59',
    'request.reasonForCancellation': 'Item not available',
    'request.additionalInfo': 'Additional information regarding the request cancellation',
  },
  loan: {
    'loan.dueDate': 'Dec 31, 2019',
    'loan.dueDateTime': 'Dec 31, 2019 22:00',
    'loan.initialBorrowDate': 'Jan 1, 2019',
    'loan.initialBorrowDateTime': 'Jan 1, 2019 11:00',
    'loan.checkedInDate': 'Dec 15, 2019',
    'loan.checkedInDateTime': 'Dec 15, 2019 13:24',
    'loan.numberOfRenewalsAllowed': '10',
    'loan.numberOfRenewalsTaken': '2',
    'loan.numberOfRenewalsRemaining': '8',
  },
  effectiveLocation: {
    'item.effectiveLocationSpecific': 'Main Library Reserve',
    'item.effectiveLocationLibrary': 'Main Library',
    'item.effectiveLocationCampus': 'South Campus',
    'item.effectiveLocationInstitution': 'Opentown University',
  },
  feeFineCharge: {
    'feeCharge.owner': 'Main Library',
    'feeCharge.type': 'Damaged Item',
    'feeCharge.paymentStatus': 'Outstanding',
    'feeCharge.date': 'Jun 30, 2020',
    'feeCharge.dateTime': 'Jun 30, 2020 11:00',
    'feeCharge.amount': '$15.00',
    'feeCharge.remainingAmount': '$5.00',
    'feeCharge.additionalInfo': 'This is a text field intended to provide additional information for the patron regarding the fee/fine.'
  },
  feeFineAction: {
    'feeAction.type': 'Waived partially',
    'feeAction.date': 'Jul 10, 2020',
    'feeAction.dateTime': 'Jul 10, 2020 8:00',
    'feeAction.amount': '$5.00',
    'feeAction.remainingAmount': '$10.00',
    'feeAction.additionalInfo': 'Cost to repair less than expected.',
  },
};

export default formats;
