const formats = {
  item: {
    'item.title': 'The Wines of Italy',
    'item.primaryContributor': 'Thomas, George B.',
    'item.allContributors': 'Finney, Ross L.; Weir, Maurice D.',
    'item.barcode': '31924001521792',
    'item.barcodeImage': '<Barcode>31924001521792</Barcode>',
    'item.callNumber': 'TK7871.15.F4 S67 1988',
    'item.callNumberPrefix': 'New & Noteworthy',
    'item.callNumberSuffix': 'Handbook',
    'item.copy': 'c.2',
    'item.enumeration': 'no.1-3',
    'item.volume': 'v.27',
    'item.chronology': '1964-1967 (Board)',
    'item.yearCaption': 'Convention photographs 1911-1960',
    'item.loanType': 'Course reserves',
    'item.materialType': 'Serial',
    'item.numberOfPieces': '7',
    'item.descriptionOfPieces': '7 maps in pocket',
    'item.lastCheckedInDateTime': 'Jun 15, 2019 10:00',
    'item.fromServicePoint': 'Circulation Desk - South Library',
    'item.toServicePoint': 'Circulation Desk - Main Library',
  },
  effectiveLocation: {
    'item.effectiveLocationInstitution': 'Opentown University',
    'item.effectiveLocationCampus': 'South Campus',
    'item.effectiveLocationLibrary': 'Main Library',
    'item.effectiveLocationSpecific': 'Main Library Reserve',
  },
  request: {
    'request.servicePointPickup': 'Circulation Desk - Main Library',
    'request.requestExpirationDate': 'Jun 30, 2020 23:59',
    'request.holdShelfExpirationDate': 'Mar 31, 2020 23:59',
    'request.requestID': '987321654',
  },
  requestDeliveryAddress: {
    'request.deliveryAddressType': 'Office',
    'requester.addressLine1': '123 Campus Drive',
    'requester.addressLine2': '226 Classroom Building, Box 12345',
    'requester.city': 'Los Angeles',
    'requester.stateProvRegion': 'CA',
    'requester.zipPostalCode': '90048',
    'requester.country': 'USA',
  },
  requester: {
    'requester.firstName': 'James',
    'requester.lastName': 'Smith',
    'requester.middleName': 'Adam',
    'requester.barcode': '456123789',
    'requester.barcodeImage': '<Barcode>456123789</Barcode>',
  },
  staffSlip: {
    'staffSlip.Name': 'Transit',
  },
};

export default formats;
